lang: "en-us"
title: RobOtter
short_name: RobOtter
email: contact@robotter.ai
tel:
whatsapp:
whatsapp_link:
author: RobOtter
url: https://yourtrading-ai.github.io
address:
description: > # this means to ignore newlines until "show_excerpts:"
  Create Machine Learning models without code.
  Publish your predictions on Chainlink.
  Automate trading and get paid.

show_excerpts: true # set to true to show excerpts on the homepage



style:
  primary: "#FFFF00"
  secondary: "#1DBAB1"
  background: "#151621"
  hover: "#FFFF00"
  active: "#FFFF00"
  container-max-width: 1120px

logo: assets/Robotter/Logo-Robotter.svg
defaultHeaderImage:
cta_text_default: "Contact"
cta_href_default: "/#contact"

amp-link-variable-allowed-origin: "https://app.wechselgott.com"
data-amp-addparams:

# Contact
static_email:

# Consent
consent: false

custom_scripts:
#  gtag: GTM-P8V4Q3S

# AMP-Analytics
analytics:
  provider: false # false (default), "google", "google-universal", "custom"
#  googleadwords:
#    tracking_id: AW-756554075
#  googleanalytics:
#    tracking_id: UA-132798592-1
#  facebookpixel:
#    tracking_id: 669247813944831
#  gtags:
#    - GTM-P8V4Q3S

# Experiments
experiments:
#  experimentName: Startseiten-Experiment-Ersparnis
#  gaPropertyID: UA-132798592-1
#  gaExperimentID: CW8M_WYZSXCjiP1CK4dDT

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%d.%m.%Y"

  # generate social links in footer
  social_links:
#    twitter: jekyllrb
#    github:  jekyll
#    rss: rss
    # dribbble: jekyll
#     facebook: wechselgott
    # flickr:   jekyll
#     instagram: wechselgott_app
#     linkedin: wechselgott
#     xing: company/finum
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Defaults
defaults:
  # default
  - scope:
      path: ""
    values:
      amp-sidebar: true
      nocta: true
      image: /assets/WechselGott/Logo-WechselGott-Typo-Right.svg

  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      meta: BlogPosting
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: page
      header: true
      footer: false

# Outputting
permalink: /:title/
paginate: 26 # amount of posts to show
paginate_path: "/blog/page:num/"
timezone: DE # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Collections
collections:
  events:
    output: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Reading Files
include:
  - .htaccess
  - _pages

exclude:
  - .idea/
  - script
  - src
  - screenshot.png
  - node_modules
  - CNAME
  - package.json
  - package-lock.json
  - "*.txt"
  - "*.markdown"
  - "*.gemspec"
  - "*.sh"
  - "*/Tarifrechner-Dateien"

plugins:
 - jekyll-feed
 - jekyll-paginate
 - jekyll-sitemap
 - jekyll-seo-tag
